# Generated by Django 2.2.2 on 2019-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to=''),
        ),
    ]
