# Generated by Django 2.2.2 on 2019-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190822_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
    ]
